version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2026 The Axonarium contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "data/**"
SPDX-FileCopyrightText = "2026 The Axonarium contributors"
SPDX-License-Identifier = "CC-BY-4.0"
